/**
 * Search UI over the static Pagefind index (generated by `pagefind --site dist` after the Astro build).
 * This module is only ever loaded on /search/ or when the header dialog is opened.
 */
type PagefindResult = {
  url: string;
  excerpt: string;
  meta: { title?: string; type?: string; technology?: string; difficulty?: string };
  filters: Record<string, string[]>;
};
type PagefindApi = {
  options: (o: Record<string, unknown>) => Promise<void>;
  init: () => Promise<void>;
  debouncedSearch: (
    term: string,
    opts?: Record<string, unknown>,
    ms?: number,
  ) => Promise<{ results: { data: () => Promise<PagefindResult> }[]; unfilteredResultCount: number } | null>;
};

let pagefind: Promise<PagefindApi> | undefined;

function loadPagefind(): Promise<PagefindApi> {
  pagefind ??= (async () => {
    const url = "/pagefind/pagefind.js";
    const api = (await import(/* @vite-ignore */ url)) as PagefindApi;
    await api.options({
      baseUrl: "/",
      // Prefer title/heading matches over long body matches (see docs/DECISIONS.md D-009).
      ranking: { termFrequency: 0.6, termSaturation: 1.4, pageLength: 0.5, termSimilarity: 1.2 },
      excerptLength: 22,
    });
    await api.init();
    return api;
  })();
  return pagefind;
}

function safeExcerpt(html: string): DocumentFragment {
  const frag = document.createDocumentFragment();
  const doc = new DOMParser().parseFromString(html, "text/html");
  doc.body.childNodes.forEach((n) => {
    if (n.nodeName === "MARK") {
      const m = document.createElement("mark");
      m.textContent = n.textContent;
      frag.append(m);
    } else {
      frag.append(document.createTextNode(n.textContent ?? ""));
    }
  });
  return frag;
}

export function mountSearch(root: HTMLElement) {
  if (root.dataset.mounted) return root.querySelector<HTMLInputElement>("input[type=search]")?.focus();
  root.dataset.mounted = "true";
  const input = root.querySelector<HTMLInputElement>("input[type=search]")!;
  const status = root.querySelector<HTMLElement>("[data-search-status]")!;
  const list = root.querySelector<HTMLUListElement>("[data-search-results]")!;
  const filters = root.querySelector<HTMLElement>("[data-search-filters]")!;
  const difficulty = root.querySelector<HTMLSelectElement>("select[data-search-difficulty]");
  const clear = root.querySelector<HTMLButtonElement>("[data-search-clear]");

  let type = "All";
  let seq = 0;

  filters.querySelectorAll<HTMLButtonElement>("button[data-type]").forEach((b) => {
    b.addEventListener("click", () => {
      type = b.dataset.type ?? "All";
      filters.querySelectorAll("button").forEach((x) => x.setAttribute("aria-pressed", String(x === b)));
      void run();
    });
  });

  function setStatus(msg: string) {
    status.textContent = msg;
  }

  function showEmpty(term: string) {
    list.replaceChildren();
    const li = document.createElement("li");
    li.className = "empty-state";
    const h = document.createElement("h3");
    h.textContent = `No results for “${term}”`;
    const p = document.createElement("p");
    p.textContent = "Try a broader technology, a concept instead of an exact phrase, or remove a filter.";
    const a = document.createElement("a");
    a.href = "/data-engineering/roadmap/";
    a.textContent = "Browse the Data Engineering roadmap";
    li.append(h, p, a);
    list.append(li);
  }

  async function run() {
    const term = input.value.trim();
    const mySeq = ++seq;
    if (clear) clear.hidden = !term;
    if (!term) {
      list.replaceChildren();
      setStatus("");
      return;
    }
    setStatus("Searching…");
    let api: PagefindApi;
    try {
      api = await loadPagefind();
    } catch {
      list.replaceChildren();
      setStatus("");
      const li = document.createElement("li");
      li.className = "status-message";
      li.textContent =
        "Search is not available right now. The search index is created during the production build; use the links below to browse instead.";
      list.append(li);
      return;
    }
    const f: Record<string, string> = {};
    if (type !== "All") f.type = type;
    if (difficulty?.value) f.difficulty = difficulty.value;
    const res = await api.debouncedSearch(term, { filters: f }, 120);
    if (!res || mySeq !== seq) return; // superseded by newer input
    const data = await Promise.all(res.results.slice(0, 12).map((r) => r.data()));
    if (mySeq !== seq) return;
    if (!data.length) {
      setStatus("0 results");
      showEmpty(term);
      return;
    }
    list.replaceChildren(
      ...data.map((d) => {
        const li = document.createElement("li");
        const a = document.createElement("a");
        a.className = "search-result";
        a.href = d.url;
        const meta = document.createElement("span");
        meta.className = "search-result__meta";
        meta.textContent = [d.meta.type, d.meta.technology, d.meta.difficulty].filter(Boolean).join(" · ");
        const title = document.createElement("span");
        title.className = "search-result__title";
        title.textContent = d.meta.title ?? d.url;
        const ex = document.createElement("span");
        ex.className = "search-result__excerpt";
        ex.append(safeExcerpt(d.excerpt));
        a.append(meta, title, ex);
        li.append(a);
        return li;
      }),
    );
    const n = res.results.length;
    setStatus(`${n} result${n === 1 ? "" : "s"}${n > 12 ? " (showing the first 12)" : ""}`);
  }

  input.addEventListener("input", () => void run());
  difficulty?.addEventListener("change", () => void run());
  clear?.addEventListener("click", () => {
    input.value = "";
    void run();
    input.focus();
  });
  input.focus();
  // Support /search/?q=term deep links from the 404 page etc.
  const q = new URLSearchParams(location.search).get("q");
  if (q) {
    input.value = q;
    void run();
  }
}
